{ config, lib, pkgs, ... }:
{
  imports = [
    ../../../Modules/PrintersScanners/LaserJetPrinter
    ../../../Modules/PrintersScanners/EpkowaScanner
    ../../../Modules/PrintersScanners/Daemon
    ../../../Modules/PrintersScanners/TelegramBot
    ../../../Modules/Monitoring/TelegramAlerts
    ../../../Modules/System/AutoRebuildOnPush
  ];

  networking.hostName = "printscan";
  system.stateVersion = "25.05";

  hardware.enableRedistributableFirmware = true;

  # Filesystems — RPi4 SD card layout (set by sd-image module on first flash,
  # then referenced directly for subsequent nixos-rebuild).
  # The sd-image module is only used for CI image builds, not runtime config.
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
  };
  fileSystems."/boot/firmware" = {
    device = "/dev/disk/by-label/FIRMWARE";
    fsType = "vfat";
  };

  # Use the generic aarch64 kernel instead of the RPi-specific one.
  # The nixos-hardware raspberry-pi-4 module selects linuxPackages_rpi4
  # which uses a custom kernel (linux-rpi) that is NOT in cache.nixos.org.
  # Every nixpkgs update would trigger a kernel recompile — 4-8 hours on
  # the Pi, 1-2 hours under QEMU emulation on CI.
  # The generic kernel is always cached and downloads in seconds.
  # Trade-off: loses RPi-specific patches (GPU/display, camera, HAT overlays)
  # which are irrelevant for a headless print/scan server.
  #
  # To restore RPi-specific kernel (requires own cachix or patience):
  #   boot.kernelPackages = pkgs.linuxPackages_rpi4;
  boot.kernelPackages = pkgs.linuxPackages;

  networking = {
    useDHCP = true;
    firewall = {
      enable = true;
      allowedTCPPorts = [ 22 ];
    };
  };

  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = false;
    };
  };

  users.users.administrator = {
    isNormalUser = true;
    extraGroups = [ "wheel" "scanner" "lp" ];
    openssh.authorizedKeys.keys = [
      "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLESV1KGuOruuV5JdUr8wS8iQyIfEeYdJz2MC5zNCOjoTqzJpA3j5e3kdXbyFczRK25o5bFlThHzK2kmwmCE4zE= printscan-administrator"
    ];
  };
  users.users.root.hashedPassword = "!";  # no password, login disabled
  security.sudo.wheelNeedsPassword = false;

  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
  };
  nixpkgs.config.allowUnfree = true;

  system.autoUpgrade = {
    enable = true;
    flake = "/etc/nixos#default";
    dates = "*-*-01 02:00";  # first day of each month at 2 AM
    randomizedDelaySec = "6h"; # spreads to 2-8 AM
    allowReboot = true;      # unattended machine, reboot if kernel changed
    flags = [ "--refresh" ]; # always pull latest from GitHub
  };

  # Generate /etc/nixos/flake.nix on first boot (or if missing).
  # This local flake owns the lock file and controls nixpkgs version.
  system.activationScripts.localFlake = ''
    if [ ! -f /etc/nixos/flake.nix ]; then
      mkdir -p /etc/nixos
      cat > /etc/nixos/flake.nix << 'FLAKE'
# GENERATED by NixOS activation script — do not edit.
# To customize, delete this file and create your own.
# Source: Machines/RPi4/PrintScanServer/configuration.nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixos-hardware.url = "github:NixOS/nixos-hardware";
    upstream = {
      url = "github:hypersw/HyperNix";                   # ← remote flake
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.nixos-hardware.follows = "nixos-hardware";
    };
  };

  outputs = { upstream, ... }: {
    nixosConfigurations.default =
      upstream.nixosConfigurations.PrintScanServer;       # ← configuration name
  };
}
FLAKE
    fi
  '';

  # Update flake inputs (nixpkgs, upstream) before each auto-upgrade
  systemd.services.nixos-upgrade.preStart = "nix flake update --flake /etc/nixos";

  # Expand root partition to fill the SD card on first boot
  boot.growPartition = true;

  # SD card longevity
  boot.tmp.useTmpfs = true;
  services.journald.extraConfig = "Storage=volatile";
  fileSystems."/".options = [ "noatime" ];

  # Memory management: zram first, disk swap as OOM safety net
  zramSwap = {
    enable = true;
    memoryPercent = 50;   # ~2 GB compressed swap in RAM
    algorithm = "zstd";
  };
  swapDevices = [{
    device = "/var/swapfile";
    size = 2048;  # 2 GB on disk — last resort before OOM killer
  }];
  boot.kernel.sysctl."vm.swappiness" = 1;  # almost never touch disk swap

  environment.systemPackages = with pkgs; [
    htop
    usbutils
    sane-backends
  ];

  # ── Secrets (sops-nix) ──
  # Decryption key derived from SSH host ed25519 key — no extra key management.
  # Secrets are encrypted in the repo, decrypted to /run/secrets/ at activation.
  sops = {
    defaultSopsFile = ./secrets/telegram.yaml;
    age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
    secrets.telegram-token = {};
  };

  # ── Module enablement ──
  services.laserjet-printer.enable = true;
  services.epkowa-scanner.enable = true;
  services.printscan-daemon.enable = false;
  services.printscan-telegram-bot.enable = false;

  services.telegram-alerts = {
    enable = true;
    tokenFile = config.sops.secrets.telegram-token.path;
    alertsChatId = "PLACEHOLDER";  # TODO: set after creating Telegram groups
    logChatId = "PLACEHOLDER";     # TODO: set after creating Telegram groups
  };

  # Poll upstream flake for config changes every 5 min, rebuild if changed.
  # Only updates the 'upstream' input (HyperNix), not nixpkgs —
  # nixpkgs is updated by the monthly auto-upgrade service.
  services.auto-rebuild-on-push.enable = true;
}
