{ config, lib, pkgs, ... }:
{
  imports = [
    ../../../Modules/PrintersScanners/LaserJetPrinter
    ../../../Modules/PrintersScanners/EpkowaScanner
    ../../../Modules/PrintersScanners/Daemon
    ../../../Modules/PrintersScanners/TelegramBot
    ../../../Modules/Monitoring/TelegramAlerts
    ../../../Modules/System/AutoRebuildOnPush
  ];

  networking.hostName = "printscan";
  system.stateVersion = "25.05";

  # Required for RPi4 WiFi (brcmfmac) and Bluetooth firmware blobs.
  hardware.enableRedistributableFirmware = true;

  # Filesystems — RPi4 SD card layout (set by sd-image module on first flash,
  # then referenced directly for subsequent nixos-rebuild).
  # The sd-image module is only used for CI image builds, not runtime config.
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
  };
  fileSystems."/boot/firmware" = {
    device = "/dev/disk/by-label/FIRMWARE";
    fsType = "vfat";
  };

  # Use the generic aarch64 kernel instead of the RPi-specific one.
  # The nixos-hardware raspberry-pi-4 module selects linuxPackages_rpi4
  # which uses a custom kernel (linux-rpi) that is NOT in cache.nixos.org.
  # Every nixpkgs update would trigger a kernel recompile — 4-8 hours on
  # the Pi, 1-2 hours under QEMU emulation on CI.
  # The generic kernel is always cached and downloads in seconds.
  # Trade-off: loses RPi-specific patches (GPU/display, camera, HAT overlays)
  # which are irrelevant for a headless print/scan server.
  #
  # To restore RPi-specific kernel (requires own cachix or patience):
  #   boot.kernelPackages = pkgs.linuxPackages_rpi4;
  boot.kernelPackages = pkgs.linuxPackages;

  networking = {
    useDHCP = true;
    firewall = {
      enable = true;
      allowedTCPPorts = [ 22 ];
      allowedUDPPorts = [ 5353 ];  # mDNS (Avahi)
    };

    # WiFi client — connect to IoT PPSK network
    wireless = {
      enable = true;
      secretsFile = config.sops.templates."wpa-secrets".path;
      # Disable Wi-Fi Direct (P2P) — RPi4's BCM43455 doesn't support the
      # required DFS/wide channels, causing constant brcmf_set_channel errors.
      extraConfig = "p2p_disabled=1";
      networks."HyperAir.IotPsk" = {
        pskRaw = "ext:psk_iot";  # pskRaw outputs unquoted — required for ext: refs
        hidden = true;  # SSID not broadcast — probe actively
      };
    };
  };

  # Ensure wpa_supplicant starts after sops decrypts secrets
  systemd.services.wpa_supplicant = {
    after = [ "sops-nix.service" ];
    wants = [ "sops-nix.service" ];
  };

  # Advertise hostname on the LAN via mDNS (multicast DNS).
  # Lets clients reach this machine as printscan.local without DNS config.
  services.avahi = {
    enable = true;
    nssmdns4 = true;  # resolve .local names on this machine too
    publish = {
      enable = true;
      addresses = true;
    };
  };

  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = false;
    };
  };

  users.users.administrator = {
    isNormalUser = true;
    extraGroups = [ "wheel" "scanner" "lp" ];  # scanner+lp for SANE/CUPS access
    openssh.authorizedKeys.keys = [
      "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLESV1KGuOruuV5JdUr8wS8iQyIfEeYdJz2MC5zNCOjoTqzJpA3j5e3kdXbyFczRK25o5bFlThHzK2kmwmCE4zE= printscan-administrator"
    ];
  };
  users.users.root.hashedPassword = "!";  # disable root login entirely
  # Headless device — no interactive console for password entry.
  security.sudo.wheelNeedsPassword = false;

  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;  # hardlink identical store paths — saves SD card space
    };
    # Run gc once a month, the day after system.autoUpgrade. On-push rebuilds
    # don't trigger gc — between monthly upgrades the store barely changes, and
    # gc scans are writes the SD card doesn't need. The 1-day lag past
    # autoUpgrade leaves a rollback window; --delete-older-than 30d then keeps
    # at least the previous month's generation once we collect.
    gc = {
      automatic = true;
      dates = "*-*-02 04:00";
      randomizedDelaySec = "6h";
      options = "--delete-older-than 30d";
      persistent = true;
    };
  };
  nixpkgs.config.allowUnfree = true;

  system.autoUpgrade = {
    enable = true;
    flake = "/etc/nixos#default";
    dates = "*-*-01 02:00";  # first day of each month at 2 AM
    randomizedDelaySec = "6h"; # spreads to 2-8 AM
    allowReboot = true;      # unattended machine, reboot if kernel changed
    flags = [ "--refresh" ]; # always pull latest from GitHub
  };

  # Generate /etc/nixos/flake.nix on first boot (or if missing).
  # This local flake owns the lock file and controls nixpkgs version.
  system.activationScripts.localFlake = ''
    if [ ! -f /etc/nixos/flake.nix ]; then
      mkdir -p /etc/nixos
      cat > /etc/nixos/flake.nix << 'FLAKE'
# GENERATED by NixOS activation script — do not edit.
# To customize, delete this file and create your own.
# Source: Machines/RPi4/PrintScanServer/configuration.nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixos-hardware.url = "github:NixOS/nixos-hardware";
    upstream = {
      url = "github:hypersw/HyperNix";                   # ← remote flake
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.nixos-hardware.follows = "nixos-hardware";
    };
  };

  outputs = { upstream, ... }: {
    nixosConfigurations.default =
      upstream.nixosConfigurations.PrintScanServer;       # ← configuration name
  };
}
FLAKE
    fi
  '';

  # Update flake inputs (nixpkgs, upstream) before each auto-upgrade.
  # Without this, auto-upgrade would rebuild from the stale lock file
  # and never pick up new nixpkgs or upstream changes.
  systemd.services.nixos-upgrade.preStart = "nix flake update --flake /etc/nixos";

  # Expand root partition to fill the SD card on first boot
  boot.growPartition = true;

  # SD card longevity — minimize writes to extend flash lifetime.
  boot.tmp.useTmpfs = true;                          # /tmp in RAM, not on disk
  fileSystems."/".options = [ "noatime" ];            # skip access-time writes
  # Journal in RAM (volatile) saves writes but loses history across reboots.
  # On a settled Pi where everything just works, that's the right trade-off.
  # While the system is still being iterated on, we need logs from previous
  # boots to diagnose stalls/crashes — so keep the journal persistent for
  # now. Flip back to volatile once the config stabilises.
  #   services.journald.extraConfig = "Storage=volatile";

  # Memory management: zram first, disk swap as OOM safety net
  zramSwap = {
    enable = true;
    memoryPercent = 50;   # ~2 GB compressed swap in RAM
    algorithm = "zstd";
  };
  swapDevices = [{
    device = "/var/swapfile";
    size = 2048;  # 2 GB on disk — last resort before OOM killer
  }];
  boot.kernel.sysctl."vm.swappiness" = 1;  # almost never touch disk swap

  environment.systemPackages = with pkgs; [
    htop
    usbutils
    sane-backends
  ];

  # ── Secrets (sops-nix) ──
  # Decryption key derived from SSH host ed25519 key — no extra key management.
  # Secrets are encrypted in the repo, decrypted to /run/secrets/ at activation.
  sops = {
    defaultSopsFile = ./secrets/secrets.yaml;
    age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

    # Monitoring bot
    secrets.telegram-monitoring-bot-token = {};
    secrets.telegram-alerts-chat-id = {};
    secrets.telegram-log-chat-id = {};

    # Print/scan bot
    secrets.printscan-bot-token = {};

    # WiFi
    secrets.wifi-iot-psk = {};

    # wpa_supplicant secrets file — maps sops secret to ext: reference.
    # wpa_supplicant runs sandboxed as its own user, needs read access.
    templates."wpa-secrets" = {
      content = "psk_iot=${config.sops.placeholder."wifi-iot-psk"}";
      owner = "wpa_supplicant";
    };
  };

  # Enable x86_64 binary emulation via qemu-user binfmt.
  # The EpkowaScanner module's proxy/stub approach spawns a short-lived
  # x86_64 helper per scan (see EpkowaStubX64/PROTOCOL.md). qemu-user runs
  # the helper transparently. USB stays aarch64-native in our code — the
  # helper does pure CPU work (ESC/I byte munging), which qemu-user handles
  # fine. This also lets nix build x86_64 dependencies under emulation.
  boot.binfmt.emulatedSystems = [ "x86_64-linux" ];

  # ── Module enablement ──
  services.laserjet-printer.enable = true;
  services.epkowa-scanner.enable = true;
  services.printscan-daemon.enable = true;

  services.printscan-telegram-bot = {
    enable = true;
    tokenFile = config.sops.secrets.printscan-bot-token.path;
    allowedUsers = [
      { id = 1398173959; name = "hypersw"; }
      { id = 2074641026; name = "ol"; }
      { id = 6935307009; name = "alice"; }
    ];
  };

  services.telegram-alerts = {
    enable = true;
    tokenFile = config.sops.secrets.telegram-monitoring-bot-token.path;
    alertsChatIdFile = config.sops.secrets.telegram-alerts-chat-id.path;
    logChatIdFile = config.sops.secrets.telegram-log-chat-id.path;
    # Revision info is passed from the flake (see flake.nix specialArgs or module overlay)
    # These are set by the flake where self.rev and nixpkgs.rev are available.
  };

  # Poll upstream flake for config changes every 5 min, rebuild if changed.
  # Only updates the 'upstream' input (HyperNix), not nixpkgs —
  # nixpkgs is updated by the monthly auto-upgrade service.
  services.auto-rebuild-on-push.enable = true;
}
